name: Drupi
api: "1.0.0"
main: net.stacket.drupi.legacy.MainPlugin
author: ["Hundeklemmen", "Stacket Group", "SlickNicky10"]
version: "1.0.0"
description: "Minecraft development made easy."
website: "https://stacket.net/drupi"
softdepend: [PlaceholderAPI, WorldGuard, Skript, TitleManager, LabyModAPI]
commands:
  drupi:
    description: Interacting with the plugin
    usage: /drupi [args]