name: Drupi
main: net.stacket.drupi.bungeecord.MainPlugin
version: "1.0.0"
author: "Stacket Group"
description: "Minecraft development made easy."
website: "https://stacket.net/drupi"
softdepend: [LabyModAPI]